### ISSUE TITLE
How can i slove this error ?

### ISSUE THREAD

**Issue by vishmayleeway** [owlclaw0803/PhotoEditing#1]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/it.repix.android-1/base.apk"],nativeLibraryDirectories=[/data/app/dit.repix.android-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "librepix.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:1076)
        at it.repix.android.GL2JNILib.<clinit>(GL2JNILib.java:99)
        at it.repix.android.RepixActivity.onCreate(RepixActivity.java:639)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Moseqi** [comment]
Did you solve it? @vishmayleeway

**Comment by vishmayleeway** [comment]
@Moseqi No , Brother he used NDK lib and don't upload in his repository.

**Comment by Moseqi** [comment]
Create jniLibs folder in src-> main folder in your project

Copy armeabi-v7a,x86 folder from this project's libs folder.(It contains .so file) to jniLibs of your projects

Rebuild and run!

@vishmayleeway

**Comment by vishmayleeway** [comment]
@Moseqi bro you solved it and run its ?

**Comment by Moseqi** [comment]
Yes. I did @vishmayleeway

**Comment by vishmayleeway** [comment]
oh ,Great brother.Actually   i can't solve  "net.simonvt.menudrawer.LeftDrawer " this Custom class i have tried gradle compile  file , jar file but still i got class not found error can you help me bro ?

**Comment by Moseqi** [comment]
In which class you are getting this error? Please elaborate.

**Comment by vishmayleeway** [comment]
Hello  @Moseqi   i got this error "Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class net.simonvt.menudrawer.LeftDrawer" i have already import  this  " implementation 'net.simonvt.menudrawer:menudrawer:3.0.6' " in gradle but still got this error .

**Comment by Moseqi** [comment]
There is no gradle 'net.simonvt.menudrawer:menudrawer:3.0.6'' in this project maybe. Are you talking about this project or other. Please provide your layout xml file name in this project where you getting this error.

**Comment by vishmayleeway** [comment]
You Run this project  on Android Studio Or Eclipse ?

In Main.xml  i got error on 8th line. 

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:animateLayoutChanges="true">

    <net.simonvt.menudrawer.LeftDrawer  // here i got error
        android:id="@+id/drawer"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:orientation="vertical"
        app:mdMenuSize="@dimen/sidemenu_width">

        <LinearLayout
            android:id="@+id/mdMenu"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:background="@color/sideMenuBackground"
            android:orientation="vertical">

            <it.repix.android.LeftSideListView
                android:id="@+id/sidelistview"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:divider="@null"
                android:dividerHeight="0.0dip"
                android:focusableInTouchMode="true" />
        </LinearLayout>

        <net.simonvt.menudrawer.RightDrawer
            android:id="@+id/sharedrawer"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:orientation="vertical"
            app:mdMenuSize="@dimen/sidemenu_width">

            <LinearLayout
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:background="@color/sideMenuBackground"
                android:orientation="vertical">

                <it.repix.android.RightSideListView
                    android:id="@+id/sharelistview"
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content"
                    android:divider="@null"
                    android:dividerHeight="0.0dip"
                    android:focusableInTouchMode="true" />
            </LinearLayout>

            <FrameLayout
                android:id="@+id/container"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:animateLayoutChanges="true">

                <it.repix.android.GL2JNIView
                    android:id="@+id/repix_gl"
                    android:layout_width="fill_parent"
                    android:layout_height="fill_parent" />

                <View
                    android:layout_width="fill_parent"
                    android:layout_height="fill_parent"
                    android:background="@android:color/transparent" />

                <LinearLayout
                    android:id="@+id/webviewlayout"
                    android:layout_width="fill_parent"
                    android:layout_height="fill_parent"
                    android:background="@drawable/background"
                    android:orientation="vertical">

                    <it.repix.android.RepixWebView
                        android:id="@+id/webview"
                        android:layout_width="fill_parent"
                        android:layout_height="fill_parent"
                        android:visibility="invisible" />
                </LinearLayout>
            </FrameLayout>
        </net.simonvt.menudrawer.RightDrawer>
    </net.simonvt.menudrawer.LeftDrawer>

    <LinearLayout
        android:id="@+id/splash"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_centerInParent="true"
        android:alpha="1.0"
        android:background="#ffdf4d4d"
        android:orientation="vertical">

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:layout_marginTop="@dimen/startup_logo_top"
            android:scaleType="centerCrop"
            android:src="@drawable/splash" />
    </LinearLayout>
</FrameLayout>

**Comment by Moseqi** [comment]
Just take a single activity and pass image uri to RepixActivity. You don't have to follow like in this demo.

Example
 Intent intent = new Intent(getApplicationContext(), RepixActivity.class);
        intent.putExtra("imageUri", imageUri);
        intent.putExtra("orientation", 0);
        startActivity(intent);

**Comment by Moseqi** [comment]
RepixActvity will done all the procedure. And yes you have to modify it's code too. Recently i have known that this lib is already an app (or was i don't know.)
But it may be illegal. Please use it as learning purpose. Do not release an app with this same functionality.
